-- Aurora Hotel Plaza - Deluxe Sang Trọng
-- Bảng dữ liệu cho trang phòng Deluxe, dùng tiền tố cột: deluxe_abc

CREATE TABLE IF NOT EXISTS `deluxe_sang_trong` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `deluxe_abc_slug` VARCHAR(100) NOT NULL,
  `deluxe_abc_title` VARCHAR(255) NOT NULL,
  `deluxe_abc_description` TEXT,
  `deluxe_abc_hero_subtitle` VARCHAR(255),
  `deluxe_abc_price_text` VARCHAR(50),
  `deluxe_abc_per_night_text` VARCHAR(20),
  `deluxe_abc_booking_url` VARCHAR(255),
  `deluxe_abc_book_button_text` VARCHAR(100),
  `deluxe_abc_contact_hotline_label` VARCHAR(100),
  `deluxe_abc_contact_hotline` VARCHAR(50),
  `deluxe_abc_contact_email_label` VARCHAR(100),
  `deluxe_abc_contact_email_booking` VARCHAR(150),
  `deluxe_abc_contact_email_info` VARCHAR(150),
  `deluxe_abc_amenities` TEXT, -- JSON array
  `deluxe_abc_included_services` TEXT, -- JSON array
  `deluxe_abc_specs` TEXT, -- JSON array of objects {label,value}
  `deluxe_abc_gallery_main_alt` VARCHAR(255),
  `deluxe_abc_gallery_prev_label` VARCHAR(100),
  `deluxe_abc_gallery_next_label` VARCHAR(100),
  `deluxe_abc_lightbox_close_label` VARCHAR(100),
  `deluxe_abc_related_heading` VARCHAR(150),
  `deluxe_abc_related1_title` VARCHAR(150),
  `deluxe_abc_related1_price` VARCHAR(100),
  `deluxe_abc_related1_btn_text` VARCHAR(100),
  `deluxe_abc_related2_title` VARCHAR(150),
  `deluxe_abc_related2_price` VARCHAR(100),
  `deluxe_abc_related2_btn_text` VARCHAR(100),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `deluxe_sang_trong` (
  `deluxe_abc_slug`,
  `deluxe_abc_title`,
  `deluxe_abc_description`,
  `deluxe_abc_hero_subtitle`,
  `deluxe_abc_price_text`,
  `deluxe_abc_per_night_text`,
  `deluxe_abc_booking_url`,
  `deluxe_abc_book_button_text`,
  `deluxe_abc_contact_hotline_label`,
  `deluxe_abc_contact_hotline`,
  `deluxe_abc_contact_email_label`,
  `deluxe_abc_contact_email_booking`,
  `deluxe_abc_contact_email_info`,
  `deluxe_abc_amenities`,
  `deluxe_abc_included_services`,
  `deluxe_abc_specs`,
  `deluxe_abc_gallery_main_alt`,
  `deluxe_abc_gallery_prev_label`,
  `deluxe_abc_gallery_next_label`,
  `deluxe_abc_lightbox_close_label`,
  `deluxe_abc_related_heading`,
  `deluxe_abc_related1_title`,
  `deluxe_abc_related1_price`,
  `deluxe_abc_related1_btn_text`,
  `deluxe_abc_related2_title`,
  `deluxe_abc_related2_price`,
  `deluxe_abc_related2_btn_text`
) VALUES (
  'deluxe-sang-trong',
  'Phòng Deluxe Sang Trọng - Aurora Hotel Plaza',
  'Phòng Deluxe sang trọng với thiết kế hiện đại, view đẹp và đầy đủ tiện nghi cao cấp tại Aurora Hotel Plaza.',
  'Trải nghiệm không gian nghỉ dưỡng đẳng cấp với thiết kế tinh tế',
  '1.900.000 VNĐ',
  '/đêm',
  '../../dat-phong.php?room=deluxe',
  'Đặt Phòng Ngay',
  'Hotline đặt phòng:',
  '(+84-251) 391.8888',
  'Email liên hệ:',
  'booking@aurorahotelplaza.com',
  'info@aurorahotelplaza.com',
  '["Internet, Wifi miễn phí","Điện thoại IDD","TV vệ tinh","Két an toàn","Giặt ủi","Vòi sen & bồn tắm","Giường đôi: 1 cái"]',
  '["Bữa sáng miễn phí","Xông hơi","Hồ bơi","Dịch vụ phòng","Phòng Gym"]',
  '[{"label":"Diện tích:","value":"35m²"},{"label":"Sức chứa:","value":"2 người lớn"},{"label":"Loại giường:","value":"King Size"}]',
  'Phòng Deluxe - Không gian chính',
  'Ảnh trước',
  'Ảnh sau',
  'Đóng',
  'Các Loại Phòng Khác',
  'Phòng Premium Deluxe',
  '3.200.000 VNĐ/đêm',
  'Xem Chi Tiết',
  'Phòng Studio VIP',
  '4.500.000 VNĐ/đêm',
  'Xem Chi Tiết'
);

-- Lưu ý: các trường JSON đang lưu ở dạng TEXT để tương thích mọi phiên bản MySQL/MariaDB.
-- Khi triển khai CSDL với hỗ trợ JSON, có thể đổi các cột JSON sang kiểu JSON.